routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  
	return view('login');
    //return view('welcome');
});

Route::get('/cars/reporte', 'ReporteController@index');
Route::get('/cars/placa', 'PlacaController@index');

Route::get('/cars/placa', 'PlacaController@index');
Route::get('/search', 'PlacaController@search');


Route::get('/cars/disponibilidad', 'DisponibilidadController@index');









Route::resource('vehiculos', 'VehiculoController');
Route::resource('cars', 'CarController');
Route::resource('placas', 'PlacaController');
Route::resource('disponibilidad', 'DisponibilidadController');


Auth::routes();
Route::get('/main', 'MainController@index');
Route::post('/main/checklogin', 'MainController@checklogin');
Route::get('main/successlogin', 'MainController@successlogin');
Route::get('main/logout', 'MainController@logout');
Route::get('/home', 'HomeController@index')->name('home');


//Route::post('/main/checklogin', 'MainController@checklogin');

//Route::get('welcome', 'MainController@successlogin');
//Route::get('main/logout', 'MainController@logout');

app/Car.php
<?php

namespace franciscoParking;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    //
}

app/Http/Controllers/CarController.php
<?php

namespace franciscoParking\Http\Controllers;
use franciscoParking\Car;
use Illuminate\Http\Request;

class CarController extends Controller
{
   


    public function index(Request $request){
        if($request->ajax()){

            $cars = Car::all();
            return response()->json($cars, 200);

            
        }
        return view('cars.index');
    }








     public function store(Request $request){
        if($request->ajax()){
            

              
                 $min=1;
                 $max=20;

                 $randomcell = rand($min,$max);

            
            $user = \DB::table('cars')->where('celda',$randomcell)->first();

             
              
            $car = new Car();
            $car->marca = $request->input('marca');
            $car->placa = $request->input('placa');
            $car->celda = $randomcell;
            

            if(!$user){
                $car->save();
             return response()->json([
                "message" => "Carro creado correctamente.",
                "car" => $car
            ], 200);
             }
             if($user){
               return response()->json([
                "message" => "Duplicado.",
                "car" => $car
            ], 401); 
            }

            }
            

         
    }


        

     public function show($id)
    {


        $car = Car::find($id);
        return view('cars.show', compact('car'));
        //return view('vehiculos.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    public function destroy($id)
    {
       Car::destroy($id);
        return view('cars.delete');
      
    }
}

resources/views/cars/delete.blade.php
@extends('layouts.app')

@section('title', 'Carros')

@section('content')

<div class="row">
	

		

			<div class="col-sm">
	
			<div class="card text-center" style="width: 18rem;margin-top: 35px;">
			  {{-- <img class="card-img-top" src="..." alt="Card image cap"> --}}
			  <div class="card-body" >
			    <h5 class="card-title">Eliminado satisfactoriamente</h5>
			    <a href="/cars/" class="btn btn-secondary">Volver</a>
			    

			    
			  </div>
			</div>
			</div>
		

	
	</div>


@endsection

resources/views/cars/disponibilidad.blade.php
@extends('layouts.app')

@section('title', 'Vehiculos')

@section('content')

    @if(isset(Auth::user()->email))
  {{--   <div class="alert  success-block" style="text-align: right;">
     <strong>Welcome {{ Auth::user()->email }}</strong>
     <br />
     <a href="{{ url('/main/logout') }}">Logout</a>
    </div> --}}
   @else
    <script>window.location = "/main";</script>
   @endif 


<br>
<h1 style="text-align: center;">Disponibilidad de Celdas</h1>
<br>
<br>

@php







@endphp

<div class="container">


  @php $pila = array(); @endphp
  @foreach($cars as $car)
@php
 
array_push($pila, $car->celda);





$registrado =  $car->started_at;  
$actual  = date("Y-m-d h:i:sa"); 
$actual2 = date('Y-m-d H:i:s',strtotime('-3 hour',strtotime($actual)));
  

   $dteStart = new DateTime($registrado); 
   $dteEnd   = new DateTime($actual2); 

$dteDiff  = $dteStart->diff($dteEnd); 

$hora = $dteDiff->format('%H:%i:%s');

list($horas, $minutos, $segundos) = explode(':', $hora);
$hora_en_segundos = ($horas * 3600 ) + ($minutos * 60 ) + $segundos;



@endphp

			
	@endforeach
  @php 



@endphp

<table class="table">
  <thead style="text-align: center;" class="thead-dark">
    <tr>
      <th scope="col">Celda</th>
      <th scope="col">Disponibilidad</th>
    </tr>
  </thead>
  <tbody>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">1</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(1, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>


    <tr style="text-align: center;">
      <th scope="row">2</th>
      <td>@php if (!in_array(2, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">3</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(3, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">4</th>
      <td>@php if (!in_array(4, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">5</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(5, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">6</th>
      <td>@php if (!in_array(6, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">7</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(7, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" >8</th>
      <td>@php if (!in_array(8, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">9</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(9, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">10</th>
      <td>@php if (!in_array(10, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">11</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(11, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">12</th>
      <td>@php if (!in_array(12, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">13</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(13, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" >14</th>
      <td>@php if (!in_array(14, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">15</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(15, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">16</th>
      <td>@php if (!in_array(16, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">17</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(17, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">18</th>
      <td>@php if (!in_array(18, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row" style="background-color: #D0CDD7">19</th>
      <td style="background-color: #D0CDD7">@php if (!in_array(19, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>
    <tr style="text-align: center;">
      <th scope="row">20</th>
      <td>@php if (!in_array(20, $pila)) {
    echo "Disponible";} else {echo "Ocupada"; }  @endphp</td>
    </tr>

  </tbody>
</table>

	</tbody>

</table>

<a href="/"><button type="button" class="btn btn-secondary top-space"  >Volver</button></a>


</div>


@endsection

resources/views/cars/duplicate.blade.php
<template>
	<h1>CHAMPION</h1>
</template>

<script>
	
</script>

<style>
	
</style>

resources/views/cars/index.blade.php
 @extends('layouts.app')

@section('content')

<div class="container box">
   <h1 align="center" style="margin-top: 50px;">Francisco's Parking </h1><br />

 {{--   @if(isset(Auth::user()->email))
    <div class="alert  success-block" style="text-align: right;">
     <strong>Welcome {{ Auth::user()->email }}</strong>
     <br />
     <a href="{{ url('/main/logout') }}">Logout</a>
    </div>
   @else
    <script>window.location = "/main";</script>
   @endif --}}
   
   <br />
  </div>


	<add-car-btn></add-car-btn>
	<delete-car-btn></delete-car-btn>

	<cars-component></cars-component>
	<create-car-form></create-car-form>

	<a href="/"><button type="button" class="btn btn-secondary top-space" style="margin-left: 50px" >Volver</button></a>
	  			


@endsection	

resources/views/cars/placa.blade.php
@extends('layouts.app')

@section('title', 'Vehiculos')

@section('content')

    @if(isset(Auth::user()->email))
  {{--   <div class="alert  success-block" style="text-align: right;">
     <strong>Welcome {{ Auth::user()->email }}</strong>
     <br />
     <a href="{{ url('/main/logout') }}">Logout</a>
    </div> --}}
   @else
    <script>window.location = "/main";</script>
   @endif 



<div class="col-md-4">
	<form action="/search" method="get">
	
	<div class="form-group" style="margin-top: 25px; margin-bottom: 25px">
	<input type="search" name="search" class="form-control" placeholder="Introduzca Placa" >
	<span class="form-group-btn">
		<button type="submit" class="btn btn-primary" style="margin-top: 5px">Search</button>
	</span>
	</div>

</div>

@php

@endphp

<div class="container">

<table class="table footable" id="1">
  <thead class="thead-dark">
    <tr style="text-align: center;">
      <th scope="col">Celda</th>
      <th scope="col">Marca</th>
      <th scope="col">Placa</th>
      <th scope="col">Tiempo</th>
      <th scope="col">Monto a pagar</th>
      <th scope="col">Eliminar</th>
      
    </tr>
  </thead>
  @php $pila = array(); @endphp
  @foreach($cars as $car)
@php
 
array_push($pila, $car->celda);





$registrado =  $car->started_at;  
$actual  = date("Y-m-d h:i:sa"); 
$actual2 = date('Y-m-d H:i:s',strtotime('-3 hour',strtotime($actual)));
  

   $dteStart = new DateTime($registrado); 
   $dteEnd   = new DateTime($actual2); 

$dteDiff  = $dteStart->diff($dteEnd); 

$hora = $dteDiff->format('%d:%H:%i:%s');

list($dias, $horas, $minutos, $segundos) = explode(':', $hora);
$hora_en_segundos = ($dias * 86400) + ($horas * 3600 ) + ($minutos * 60 ) + $segundos;



@endphp
  <tbody>
  	
    <tr style="text-align: center;">
      <th scope="row" >{{$car->celda}}</th>
      <td>{{$car->marca}}</td>
      <td>{{$car->placa}}</td>
      <td>@php print $dteDiff->format("%d Dias %H Horas %I Minutos") @endphp </td>
      <td>@php echo (($hora_en_segundos)*30)." $"; @endphp</td>
      <td><a href="{{route('vehiculos.destroy', $car->id) }}" class="btn btn-danger">Registrar Salida</td>
      
  	</tr>
			
	@endforeach
  @php 



@endphp



	</tbody>

</table>

<a href="/"><button type="button" class="btn btn-secondary top-space"  >Volver</button></a>


</div>


@endsection

resources/views/cars/reporte.blade.php
@extends('layouts.app')

@section('title', 'Vehiculos')

@section('content')

    @if(isset(Auth::user()->email))
  {{--   <div class="alert  success-block" style="text-align: right;">
     <strong>Welcome {{ Auth::user()->email }}</strong>
     <br />
     <a href="{{ url('/main/logout') }}">Logout</a>
    </div> --}}
   @else
    <script>window.location = "/main";</script>
   @endif 



<div class="col-md-4">
	<form action="/search" method="get">
	
	<div class="form-group" style="margin-top: 25px; margin-bottom: 25px">
	<input type="search" name="search" class="form-control" placeholder="Introduzca Placa" >
	<span class="form-group-btn">
		<button type="submit" class="btn btn-primary" style="margin-top: 5px">Search</button>
	</span>
	</div>

</div>

@php

@endphp

<div class="container">
<h1 style="text-align: center;">Reporte de 5 celdas más ocupadas</h1>
<br>
<table class="table footable" id="1">
  <thead class="thead-dark">
    <tr style="text-align: center;">
      <th scope="col">Celda</th>
      <th scope="col">Marca</th>
      <th scope="col">Placa</th>
      <th scope="col">Tiempo</th>
      <th scope="col">Monto a pagar</th>
      <th scope="col">Eliminar</th>
      
    </tr>
  </thead>
  @php $pila = array(); @endphp
  @foreach($cars as $car)
@php
 
array_push($pila, $car->celda);





$registrado =  $car->started_at;  
$actual  = date("Y-m-d h:i:sa"); 
$actual2 = date('Y-m-d H:i:s',strtotime('-3 hour',strtotime($actual)));
  

   $dteStart = new DateTime($registrado); 
   $dteEnd   = new DateTime($actual2); 

$dteDiff  = $dteStart->diff($dteEnd); 

$hora = $dteDiff->format('%H:%i:%s');

list($horas, $minutos, $segundos) = explode(':', $hora);
$hora_en_segundos = ($horas * 3600 ) + ($minutos * 60 ) + $segundos;



@endphp
  <tbody>
  	
    <tr style="text-align: center;">
      <th scope="row" >{{$car->celda}}</th>
      <td>{{$car->marca}}</td>
      <td>{{$car->placa}}</td>
      <td>@php print $dteDiff->format("%H:%I:%S") @endphp </td>
      <td>@php echo (($hora_en_segundos)*30)." $"; @endphp</td>
      <td><a href="{{route('vehiculos.destroy', $car->id) }}" class="btn btn-danger">Registrar Salida</td>
      
  	</tr>
			
	@endforeach
  @php 



@endphp



	</tbody>

</table>

<a href="/"><button type="button" class="btn btn-secondary top-space"  >Volver</button></a>


</div>


@endsection

resources/views/cars/show.blade.php
@extends('layouts.app')

@section('title', 'Vehiculos')

@section('content')

{{--    @if(isset(Auth::user()->email))
    <div class="alert  success-block" style="text-align: right;">
     <strong>Welcome {{ Auth::user()->email }}</strong>
     <br />
     <a href="{{ url('/main/logout') }}">Logout</a>
    </div>
   @else
    <script>window.location = "/main";</script>
   @endif --}}


<div class="row">
	
@php
 
  $registrado =  $car->started_at;  
   $actual  = date("Y-m-d h:i:sa"); 

  

   $dteStart = new DateTime($registrado); 
   $dteEnd   = new DateTime($actual); 

$dteDiff  = $dteStart->diff($dteEnd); 

@endphp
		

			<div class="col-sm">
	
			<div class="card text-center" style="width: 18rem;margin-top: 35px;">
			  {{-- <img class="card-img-top" src="..." alt="Card image cap"> --}}
			  <div class="card-body" >
			    <h5 class="card-title">Celda</h5>
			    <p class="card-text">{{$car->celda}}</p>
			    <h5 class="card-title">Tiempo Transcurrido</h5>
			    <p class="card-text">@php print $dteDiff->format("%H:%I:%S") @endphp </p>
			    
			    <a href="/cars/" class="btn btn-secondary">Volver</a>


			    <form action="{{ route('cars.destroy', $car->id )}}" method="POST"> 
			    	<input name="_method" type="hidden" value="DELETE">
					{{ csrf_field() }}
				<input type="submit" class="btn btn-danger btn-xs" value="Eliminar"></input>
				</form>

			    
			  </div>
			</div>
			</div>
		

	
	</div>


@endsection